#*****************************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# create_project.tcl: Tcl script for re-creating project 'UDP2Prob'
#
# Generated by Vivado on Tue Feb 16 16:54:22 JST 2021
# IP Build 2185939 on Wed Apr  4 20:55:05 MDT 2018
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/queue/queue.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/CONV2MULT/CONV2MULT.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ETH_CLKGEN/ETH_CLKGEN.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/user_defines.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ARP.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/LENET.vh"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/ARRAY_REPLACE.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/struct_list.vh"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/Arbiter.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/CONV1_CORE.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/CONV1_CTRL.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/CONV1_RDPARAMS.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/CONV1_RELU.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/CONV1_RESULTS.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/CONV1_TOP.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/CONV2_CORE.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/CONV2_CTRL.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/CONV2_KNL_WINDOW.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/CONV2_RDPARAMS.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/CONV2_RELU.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/CONV2_RESULTS.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/CONV2_TOP.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CRC_ge.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/FULL1_CORE.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/FULL1_CTRL.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/FULL1_RDPARAMS.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/FULL1_RELU.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/FULL1_TOP.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/FULL2_CORE.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/FULL2_CTRL.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/FULL2_RDPARAMS.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/FULL2_RELU.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/FULL2_TOP.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/GMII2RGMII.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/IMG_CUTTER1.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/IMG_CUTTER2.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L1_POOLING.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L2_POOLING.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/LAYER1.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/LAYER2.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/LAYER3.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/LAYER4.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/LAYER5.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/LENET.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/LENET_RESULT.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/OUT_CORE.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/OUT_CTRL.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/OUT_RDPARAMS.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/OUT_TOP.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/POOL1.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/POOL1_CTRL.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/POOL1_TOP.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/POOL2.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/POOL2_CTRL.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/POOL2_TOP.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/RGMII2GMII.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/RSTGEN.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/RSTGEN2.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/T_Arbiter.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/checksum.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/csum_fast.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ping.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/trans_prob.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/udp2cnn.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/TOP.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/LENET_ARB.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/trans_image.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/recv_image.sv"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L1_PARAMS/CONV1_PARAMS.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_PARAMS00.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS0.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS1.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS2.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS3.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS4.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS5.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS6.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS7.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS8.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L4_PARAMS/FULL2_PARAMS.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L4_PARAMS/FULL2_BIAS.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L5_PARAMS/OUT_PARAMS.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L5_PARAMS/OUT_BIAS.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS9.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS10.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS11.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS12.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS13.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS14.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS15.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_BIAS.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/imports/UDP2Prob/archive_project_summary.txt"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/imports/UDP2ProbCnnMaster20210114/archive_project_summary.txt"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_BIAS.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_PARAMS01.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_PARAMS02.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_PARAMS03.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_PARAMS04.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_PARAMS05.coe"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/ip/CONV1_RESULT/CONV1_RESULT.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/CONV2_BIAS/CONV2_BIAS.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/CONV2_PARAMS00/CONV2_PARAMS00.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/CONV2_PARAMS02/CONV2_PARAMS02.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/CONV2_PARAMS03/CONV2_PARAMS03.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/CONV2_PARAMS04/CONV2_PARAMS04.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/CONV2_RESULT_1/CONV2_RESULT.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/OUT_PARAMS/OUT_PARAMS.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/CONV2_PARAMS05/CONV2_PARAMS05.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/CONV2_PARAMS01/CONV2_PARAMS01.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/OUT_MULT/OUT_MULT.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/CONV1_PARAMS/CONV1_PARAMS.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS00_1/FULL1_PARAMS00.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS01_1/FULL1_PARAMS01.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS02_1/FULL1_PARAMS02.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS03_1/FULL1_PARAMS03.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS04_1/FULL1_PARAMS04.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS05_1/FULL1_PARAMS05.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS06_1/FULL1_PARAMS06.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS07_1/FULL1_PARAMS07.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS08_1/FULL1_PARAMS08.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS09_1/FULL1_PARAMS09.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS10_1/FULL1_PARAMS10.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS11_1/FULL1_PARAMS11.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS12_1/FULL1_PARAMS12.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS13_1/FULL1_PARAMS13.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS14_1/FULL1_PARAMS14.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS15_1/FULL1_PARAMS15.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1_BIAS/FULL1_BIAS.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL2_PARAMS/FULL2_PARAMS.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL2_BIAS/FULL2_BIAS.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/OUT_BIAS/OUT_BIAS.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/CLKGEN_CNN/CLKGEN_CNN.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/CNN/ip/CONV1MULT/CONV1MULT.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL2_MULT/FULL2_MULT.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sources_1/ip/FULL1MULT/FULL1MULT.xci"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/constrs_1/NexysVideo_20181114.xdc"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sim_1/tb_RARP.v"
#    "/home/tmitsuhashi/bin/vivado_R3/UDP2Prob/UDP2Prob.srcs/sim_1/imports/UDP2Prob/tb_rarp_behav.wcfg"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "UDP2Prob"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "create_project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a200tsbg484-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "corecontainer.enable" -value "1" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "part" -value "xc7a200tsbg484-1" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/queue/queue.xci"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/CONV2MULT/CONV2MULT.xci"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ETH_CLKGEN/ETH_CLKGEN.xci"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/user_defines.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ARP.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/LENET.vh"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/ARRAY_REPLACE.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/struct_list.vh"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/Arbiter.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/CONV1_CORE.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/CONV1_CTRL.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/CONV1_RDPARAMS.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/CONV1_RELU.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/CONV1_RESULTS.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/CONV1_TOP.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/CONV2_CORE.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/CONV2_CTRL.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/CONV2_KNL_WINDOW.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/CONV2_RDPARAMS.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/CONV2_RELU.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/CONV2_RESULTS.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/CONV2_TOP.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CRC_ge.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/FULL1_CORE.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/FULL1_CTRL.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/FULL1_RDPARAMS.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/FULL1_RELU.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/FULL1_TOP.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/FULL2_CORE.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/FULL2_CTRL.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/FULL2_RDPARAMS.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/FULL2_RELU.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/FULL2_TOP.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/GMII2RGMII.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/IMG_CUTTER1.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/IMG_CUTTER2.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L1_POOLING.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L2_POOLING.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/LAYER1.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/LAYER2.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/LAYER3.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/LAYER4.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/LAYER5.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/LENET.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/LENET_RESULT.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/OUT_CORE.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/OUT_CTRL.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/OUT_RDPARAMS.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/OUT_TOP.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/POOL1.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/POOL1_CTRL.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/POOL1_TOP.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/POOL2.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/POOL2_CTRL.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/POOL2_TOP.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/RGMII2GMII.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/RSTGEN.sv" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/RSTGEN2.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/T_Arbiter.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/checksum.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/csum_fast.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ping.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/trans_prob.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/udp2cnn.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/TOP.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/LENET_ARB.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/trans_image.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/recv_image.sv"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L1_PARAMS/CONV1_PARAMS.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_PARAMS00.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS0.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS1.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS2.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS3.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS4.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS5.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS6.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS7.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS8.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L4_PARAMS/FULL2_PARAMS.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L4_PARAMS/FULL2_BIAS.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L5_PARAMS/OUT_PARAMS.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L5_PARAMS/OUT_BIAS.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS9.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS10.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS11.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS12.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS13.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS14.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_PARAMS15.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L3_PARAMS/FULL1_BIAS.coe"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/imports/UDP2Prob/archive_project_summary.txt"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/imports/UDP2ProbCnnMaster20210114/archive_project_summary.txt"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_BIAS.coe" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_PARAMS01.coe" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_PARAMS02.coe" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_PARAMS03.coe" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_PARAMS04.coe" ]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/L2_PARAMS/CONV2_PARAMS05.coe" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "queue/queue.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}

set file "ETH_CLKGEN/ETH_CLKGEN.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "generate_synth_checkpoint" -value "0" -objects $file_obj
}

set file "sources_1/user_defines.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "sources_1/ARP.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/LENET.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "CNN/ARRAY_REPLACE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "sources_1/struct_list.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "sources_1/Arbiter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/CONV1_CORE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/CONV1_CTRL.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/CONV1_RDPARAMS.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/CONV1_RELU.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/CONV1_RESULTS.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/CONV1_TOP.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/CONV2_CORE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/CONV2_CTRL.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/CONV2_KNL_WINDOW.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/CONV2_RDPARAMS.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/CONV2_RELU.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/CONV2_RESULTS.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/CONV2_TOP.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "sources_1/CRC_ge.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/FULL1_CORE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/FULL1_CTRL.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/FULL1_RDPARAMS.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/FULL1_RELU.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/FULL1_TOP.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/FULL2_CORE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/FULL2_CTRL.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/FULL2_RDPARAMS.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/FULL2_RELU.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/FULL2_TOP.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "sources_1/GMII2RGMII.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/IMG_CUTTER1.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/IMG_CUTTER2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/L1_POOLING.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/L2_POOLING.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/LAYER1.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/LAYER2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/LAYER3.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/LAYER4.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/LAYER5.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/LENET.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/LENET_RESULT.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/OUT_CORE.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/OUT_CTRL.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/OUT_RDPARAMS.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/OUT_TOP.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/POOL1.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/POOL1_CTRL.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/POOL1_TOP.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/POOL2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/POOL2_CTRL.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/POOL2_TOP.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "sources_1/RGMII2GMII.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/RSTGEN.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "sources_1/RSTGEN2.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "sources_1/T_Arbiter.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "sources_1/checksum.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "sources_1/csum_fast.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "sources_1/ping.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "sources_1/trans_prob.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "sources_1/udp2cnn.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "sources_1/TOP.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "CNN/LENET_ARB.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "sources_1/trans_image.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "sources_1/recv_image.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "TOP" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/ip/CONV1_RESULT/CONV1_RESULT.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/CONV2_BIAS/CONV2_BIAS.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/CONV2_PARAMS00/CONV2_PARAMS00.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/CONV2_PARAMS02/CONV2_PARAMS02.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/CONV2_PARAMS03/CONV2_PARAMS03.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/CONV2_PARAMS04/CONV2_PARAMS04.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/CONV2_RESULT_1/CONV2_RESULT.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/OUT_PARAMS/OUT_PARAMS.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/CONV2_PARAMS05/CONV2_PARAMS05.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/CONV2_PARAMS01/CONV2_PARAMS01.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/OUT_MULT/OUT_MULT.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/CONV1_PARAMS/CONV1_PARAMS.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS00_1/FULL1_PARAMS00.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS01_1/FULL1_PARAMS01.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS02_1/FULL1_PARAMS02.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS03_1/FULL1_PARAMS03.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS04_1/FULL1_PARAMS04.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS05_1/FULL1_PARAMS05.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS06_1/FULL1_PARAMS06.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS07_1/FULL1_PARAMS07.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS08_1/FULL1_PARAMS08.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS09_1/FULL1_PARAMS09.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS10_1/FULL1_PARAMS10.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS11_1/FULL1_PARAMS11.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS12_1/FULL1_PARAMS12.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS13_1/FULL1_PARAMS13.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS14_1/FULL1_PARAMS14.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_PARAMS15_1/FULL1_PARAMS15.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1_BIAS/FULL1_BIAS.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL2_PARAMS/FULL2_PARAMS.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL2_BIAS/FULL2_BIAS.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/OUT_BIAS/OUT_BIAS.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/CLKGEN_CNN/CLKGEN_CNN.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/CNN/ip/CONV1MULT/CONV1MULT.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL2_MULT/FULL2_MULT.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sources_1/ip/FULL1MULT/FULL1MULT.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize ${origin_dir}/UDP2Prob.srcs/constrs_1/NexysVideo_20181114.xdc]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "constrs_1/NexysVideo_20181114.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "$proj_dir/${_xil_proj_name_}.srcs/constrs_1/NexysVideo_20181114.xdc" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/UDP2Prob.srcs/sim_1/tb_RARP.v"]\
 [file normalize "${origin_dir}/UDP2Prob.srcs/sim_1/imports/UDP2Prob/tb_rarp_behav.wcfg"]\
]
set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "tb_rarp" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a200tsbg484-1 -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2018" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7a200tsbg484-1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a200tsbg484-1 -flow {Vivado Implementation 2018} -strategy "Performance_NetDelay_high" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Performance_NetDelay_high" [get_runs impl_1]
  set_property flow "Vivado Implementation 2018" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7a200tsbg484-1" -objects $obj
set_property -name "strategy" -value "Performance_NetDelay_high" -objects $obj
set_property -name "steps.place_design.args.directive" -value "ExtraNetDelay_high" -objects $obj
set_property -name "steps.phys_opt_design.is_enabled" -value "1" -objects $obj
set_property -name "steps.phys_opt_design.args.directive" -value "AggressiveExplore" -objects $obj
set_property -name "steps.route_design.args.directive" -value "NoTimingRelaxation" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
